"""Add event details

Revision ID: bb73af590a2b
Revises: dd6b03e06903
Create Date: 2025-01-25 18:35:38.153926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb73af590a2b'
down_revision = 'dd6b03e06903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('organizer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('additional_info')
        batch_op.drop_column('price')
        batch_op.drop_column('capacity')
        batch_op.drop_column('organizer')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
